# Generated by Django 4.0 on 2022-08-30 18:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('state', models.CharField(max_length=30)),
                ('state_code', models.CharField(max_length=20)),
                ('senatorial_district', models.CharField(max_length=200)),
                ('senatorial_district_code', models.CharField(max_length=100)),
                ('federal_constituency', models.CharField(max_length=200)),
                ('federal_constituency_code', models.CharField(max_length=100)),
                ('state_constituency', models.CharField(max_length=200)),
                ('state_constituency_code', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=200)),
                ('lga_code', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=200)),
                ('ward_code', models.CharField(max_length=100)),
                ('polling_unit', models.CharField(max_length=100)),
                ('polling_unit_code', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('qualifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
