# Generated by Django 4.0 on 2022-08-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='qualifications',
            field=models.CharField(choices=[('Doctorate Degree', 'Doctorate Degree'), ('Masters Degree', 'Masters Degree'), ('Honours Degree', 'Honours Degree'), ('Bachelors Degree', 'Bachelors Degree'), ('National Diploma', 'National Diploma'), ('Higher Certificate', 'Higher Certificate')], max_length=100),
        ),
    ]
