# Generated by Django 4.0 on 2022-09-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_location_remove_candidate_federal_constituency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
