# Generated by Django 4.0 on 2022-09-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='location',
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.ManyToManyField(null=True, to='candidates.Location'),
        ),
    ]
