# Generated by Django 4.0 on 2022-09-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_remove_candidate_location_candidate_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.ManyToManyField(to='candidates.Location'),
        ),
    ]
