# Generated by Django 4.0 on 2022-09-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_location_federal_constituency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
