# Generated by Django 4.0 on 2022-09-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidate_year_alter_location_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualifications',
            field=models.CharField(choices=[('Doctorate Degree', 'Doctorate Degree'), ('Masters Degree', 'Masters Degree'), ('Honours Degree', 'Honours Degree'), ('Bachelors Degree', 'Bachelors Degree'), ('National Diploma', 'National Diploma'), ('Higher Certificate', 'Higher Certificate')], max_length=100, null=True),
        ),
    ]
