# Generated by Django 4.0 on 2022-09-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_candidate_age_alter_candidate_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='year',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ManyToManyField(to='candidates.RunningPosition'),
        ),
    ]
