# Generated by Django 4.0 on 2022-09-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_alter_candidatefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatefile',
            name='file',
            field=models.URLField(null=True),
        ),
    ]
