# Generated by Django 4.1.1 on 2022-10-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_candidatefile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='candidatefile',
            name='file',
            field=models.FileField(upload_to='election-csv/'),
        ),
    ]
