# Generated by Django 4.1.1 on 2022-12-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0024_alter_candidate_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefile',
            name='type',
            field=models.CharField(choices=[('Candidate Data', 'CD'), ('Location Data', 'LD')], default='Candidate Data', max_length=14),
        ),
        migrations.AlterField(
            model_name='location',
            name='federal_constituency_code',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='polling_unit',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='location',
            name='senatorial_district_code',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_constituency_code',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
