# Generated by Django 4.1.1 on 2022-12-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0025_candidatefile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatefile',
            name='type',
            field=models.CharField(choices=[('CD', 'CandidateData'), ('LD', 'Location Data')], default='Candidate Data', max_length=14),
        ),
    ]
