# Generated by Django 4.1.1 on 2022-12-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0032_alter_candidatefile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lga',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='location',
            name='polling_unit_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='ward',
            field=models.CharField(max_length=1024),
        ),
    ]
