# Generated by Django 4.1.1 on 2022-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0033_alter_location_lga_alter_location_polling_unit_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='polling_unit_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
