# Generated by Django 4.1.1 on 2022-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0034_alter_location_polling_unit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lga',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['polling_unit_code', 'lga'], name='candidates__polling_cd4c27_idx'),
        ),
    ]
