# Generated by Django 4.1.1 on 2023-01-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0037_excelfiledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfiledata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='excelfiledata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
