# Generated by Django 4.1.1 on 2023-01-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0038_excelfiledata_created_at_excelfiledata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfiledata',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
