# Generated by Django 4.1.1 on 2023-01-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0039_excelfiledata_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfiledata',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='excelfiledata',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Uploading', 'Uploading')], max_length=50, null=True),
        ),
    ]
