# Generated by Django 4.1.1 on 2023-02-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0040_excelfiledata_message_excelfiledata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='brief',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
