# Generated by Django 4.1.1 on 2023-02-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0041_candidate_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
    ]
