# Generated by Django 4.1.1 on 2023-03-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0042_alter_candidate_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualifications',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
